package github

import (
	"fmt"
	"strings"

	"github.com/code-certification/certify/internal/domain"
)

// FormatIssueTitle generates a GitHub issue title for a decertified unit.
func FormatIssueTitle(rec domain.CertificationRecord) string {
	return fmt.Sprintf("[certification] %s — %s", rec.UnitPath, rec.Status)
}

// FormatIssueBody generates a GitHub issue body from a certification record.
func FormatIssueBody(rec domain.CertificationRecord) string {
	var b strings.Builder

	fmt.Fprintf(&b, "## Certification: %s\n\n", rec.Status)
	fmt.Fprintf(&b, "- **Unit**: `%s`\n", rec.UnitID)
	fmt.Fprintf(&b, "- **Path**: `%s`\n", rec.UnitPath)
	fmt.Fprintf(&b, "- **Score**: %.2f (%s)\n", rec.Score, rec.Grade)
	fmt.Fprintf(&b, "- **Source**: %s\n\n", rec.Source)

	if len(rec.Observations) > 0 {
		b.WriteString("### Observations\n\n")
		for _, obs := range rec.Observations {
			fmt.Fprintf(&b, "- %s\n", obs)
		}
		b.WriteString("\n")
	}

	if len(rec.Actions) > 0 {
		b.WriteString("### Recommended Actions\n\n")
		for _, act := range rec.Actions {
			fmt.Fprintf(&b, "- [ ] %s\n", act)
		}
		b.WriteString("\n")
	}

	b.WriteString("---\n")
	b.WriteString("*Generated by [certify](https://github.com/code-certification/certify)*\n")

	return b.String()
}

// BuildIssueCreateCommand constructs a `gh issue create` command.
func BuildIssueCreateCommand(title, body string, labels []string) []string {
	cmd := []string{"gh", "issue", "create", "--title", title, "--body", body}
	for _, l := range labels {
		cmd = append(cmd, "--label", l)
	}
	return cmd
}

// BuildIssueCloseCommand constructs a `gh issue close` command.
func BuildIssueCloseCommand(issueNumber string) []string {
	return []string{"gh", "issue", "close", issueNumber}
}

// BuildIssueSearchCommand constructs a `gh issue list` command to find existing issues.
// Used for deduplication — search by label + title substring.
func BuildIssueSearchCommand(unitPath string, labels []string) []string {
	cmd := []string{"gh", "issue", "list", "--state", "open", "--search", unitPath}
	for _, l := range labels {
		cmd = append(cmd, "--label", l)
	}
	cmd = append(cmd, "--json", "number,title")
	return cmd
}

// BuildIssueUpdateCommand constructs a `gh issue edit` command to update body.
func BuildIssueUpdateCommand(issueNumber, body string) []string {
	return []string{"gh", "issue", "edit", issueNumber, "--body", body}
}

// FormatGroupedIssueBody generates a single issue body for multiple related units.
func FormatGroupedIssueBody(records []domain.CertificationRecord, groupLabel string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "## Certification: %s\n\n", groupLabel)
	fmt.Fprintf(&b, "%d units require attention:\n\n", len(records))

	b.WriteString("| Unit | Status | Score | Grade |\n")
	b.WriteString("|------|--------|-------|-------|\n")
	for _, r := range records {
		fmt.Fprintf(&b, "| `%s` | %s | %.2f | %s |\n", r.UnitID, r.Status, r.Score, r.Grade)
	}
	b.WriteString("\n---\n")
	b.WriteString("*Generated by [certify](https://github.com/iksnae/code-certification/certify)*\n")
	return b.String()
}
