package workspace

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// gradeEmoji maps grades to status emoji (matches report package convention).
func gradeEmoji(grade string) string {
	switch grade {
	case "A", "A-", "B+", "B":
		return "🟢"
	case "C":
		return "🟡"
	case "D":
		return "🟠"
	case "F":
		return "🔴"
	default:
		return "⚪"
	}
}

// FormatWorkspaceCardMarkdown renders the workspace-level REPORT_CARD.md.
func FormatWorkspaceCardMarkdown(wc WorkspaceCard) string {
	var b strings.Builder

	emoji := gradeEmoji(wc.OverallGrade)

	fmt.Fprintf(&b, "# %s Workspace Report Card\n\n", emoji)
	fmt.Fprintf(&b, "**Generated:** %s\n\n", wc.GeneratedAt[:19])
	fmt.Fprintf(&b, "## %s Overall: %s (%.1f%%)\n\n", emoji, wc.OverallGrade, wc.OverallScore*100)

	fmt.Fprintf(&b, "| Metric | Value |\n")
	fmt.Fprintf(&b, "|--------|-------|\n")
	fmt.Fprintf(&b, "| Total Units | %d |\n", wc.TotalUnits)
	fmt.Fprintf(&b, "| Passing | %d |\n", wc.TotalPassing)
	fmt.Fprintf(&b, "| Failing | %d |\n", wc.TotalFailing)
	fmt.Fprintf(&b, "| Pass Rate | %.1f%% |\n", wc.PassRate*100)
	fmt.Fprintf(&b, "| Submodules | %d |\n\n", len(wc.Submodules))

	// Submodules table
	b.WriteString("### Submodules\n\n")
	b.WriteString("| Submodule | Units | Grade | Score | Pass Rate | Commit |\n")
	b.WriteString("|-----------|------:|:-----:|------:|----------:|--------|\n")

	for _, s := range wc.Submodules {
		if !s.HasCertify {
			fmt.Fprintf(&b, "| %s | — | — | — | — | *not configured* |\n", s.Name)
			continue
		}
		if s.Units == 0 {
			fmt.Fprintf(&b, "| [%s](%s/.certification/reports/index.md) | 0 | — | — | — | `%s` |\n",
				s.Name, s.Path, shortCommit(s.Commit))
			continue
		}
		fmt.Fprintf(&b, "| [%s](%s/.certification/reports/index.md) | %d | %s %s | %.1f%% | %.0f%% | `%s` |\n",
			s.Name, s.Path, s.Units, gradeEmoji(s.Grade), s.Grade, s.Score*100, s.PassRate*100, shortCommit(s.Commit))
	}
	b.WriteString("\n")

	b.WriteString("---\n\n")
	b.WriteString("*Generated by [Certify](https://github.com/iksnae/code-certification) — workspace mode*\n")

	return b.String()
}

// GenerateWorkspaceReportTree writes the workspace-level report tree.
// Returns the number of files written.
//
// Structure:
//
//	outDir/
//	  index.md                      workspace index
//	  <submodule-name>.md           per-submodule summary (configured only)
func GenerateWorkspaceReportTree(wc WorkspaceCard, outDir string) (int, error) {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return 0, fmt.Errorf("creating output dir: %w", err)
	}

	count := 0

	// Write workspace index
	indexContent := formatWorkspaceIndex(wc)
	if err := os.WriteFile(filepath.Join(outDir, "index.md"), []byte(indexContent), 0o644); err != nil {
		return 0, fmt.Errorf("writing workspace index: %w", err)
	}
	count++

	// Write per-submodule summaries (configured only)
	for _, s := range wc.Submodules {
		if !s.HasCertify {
			continue
		}

		content := formatSubmoduleSummary(s)
		filename := submoduleFilename(s.Name) + ".md"
		if err := os.WriteFile(filepath.Join(outDir, filename), []byte(content), 0o644); err != nil {
			return 0, fmt.Errorf("writing submodule summary %s: %w", s.Name, err)
		}
		count++
	}

	return count, nil
}

func formatWorkspaceIndex(wc WorkspaceCard) string {
	var b strings.Builder

	emoji := gradeEmoji(wc.OverallGrade)
	fmt.Fprintf(&b, "# %s Workspace Certification Report\n\n", emoji)
	fmt.Fprintf(&b, "[← Report Card](../REPORT_CARD.md)\n\n")
	fmt.Fprintf(&b, "**Overall:** %s %s (%.1f%%)  \n", emoji, wc.OverallGrade, wc.OverallScore*100)
	fmt.Fprintf(&b, "**Units:** %d · **Passing:** %d · **Failing:** %d\n\n", wc.TotalUnits, wc.TotalPassing, wc.TotalFailing)

	b.WriteString("## Submodules\n\n")
	b.WriteString("| Submodule | Units | Grade | Score | Pass Rate |\n")
	b.WriteString("|-----------|------:|:-----:|------:|----------:|\n")

	for _, s := range wc.Submodules {
		if !s.HasCertify || s.Units == 0 {
			continue
		}
		filename := submoduleFilename(s.Name) + ".md"
		fmt.Fprintf(&b, "| [%s](%s) | %d | %s %s | %.1f%% | %.0f%% |\n",
			s.Name, filename, s.Units, gradeEmoji(s.Grade), s.Grade, s.Score*100, s.PassRate*100)
	}

	b.WriteString("\n---\n\n")
	b.WriteString("*Generated by [Certify](https://github.com/iksnae/code-certification) — workspace mode*\n")

	return b.String()
}

func formatSubmoduleSummary(s SubmoduleSummary) string {
	var b strings.Builder

	emoji := gradeEmoji(s.Grade)
	fmt.Fprintf(&b, "# %s `%s`\n\n", emoji, s.Name)
	fmt.Fprintf(&b, "[← Workspace](index.md)\n\n")

	b.WriteString("## Summary\n\n")
	b.WriteString("| Field | Value |\n")
	b.WriteString("|-------|-------|\n")
	fmt.Fprintf(&b, "| **Path** | `%s` |\n", s.Path)
	fmt.Fprintf(&b, "| **Grade** | %s %s |\n", emoji, s.Grade)
	fmt.Fprintf(&b, "| **Score** | %.1f%% |\n", s.Score*100)
	fmt.Fprintf(&b, "| **Units** | %d |\n", s.Units)
	fmt.Fprintf(&b, "| **Passing** | %d |\n", s.Passing)
	fmt.Fprintf(&b, "| **Failing** | %d |\n", s.Failing)
	fmt.Fprintf(&b, "| **Pass Rate** | %.0f%% |\n", s.PassRate*100)
	if s.Commit != "" {
		fmt.Fprintf(&b, "| **Commit** | `%s` |\n", shortCommit(s.Commit))
	}
	if s.StateAt != "" {
		fmt.Fprintf(&b, "| **Last Certified** | %s |\n", s.StateAt[:19])
	}
	b.WriteString("\n")

	// Link to full report tree
	fmt.Fprintf(&b, "**[→ Full Report Tree](../%s/.certification/reports/index.md)**\n\n", s.Path)

	b.WriteString("---\n\n")
	b.WriteString("*Generated by [Certify](https://github.com/iksnae/code-certification) — workspace mode*\n")

	return b.String()
}

// submoduleFilename creates a safe filename from a submodule name.
// Replaces path separators with dashes.
func submoduleFilename(name string) string {
	return strings.ReplaceAll(name, "/", "-")
}

func shortCommit(commit string) string {
	if len(commit) > 7 {
		return commit[:7]
	}
	return commit
}
