package report

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// GenerateUnitReports writes individual markdown files for each unit.
// Returns the number of files written and any error.
func GenerateUnitReports(r FullReport, outDir string) (int, error) {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return 0, fmt.Errorf("creating reports directory: %w", err)
	}

	written := 0
	for _, u := range r.Units {
		filename := unitAnchor(u) + ".md"
		path := filepath.Join(outDir, filename)
		content := FormatUnitMarkdown(u, r)
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return written, fmt.Errorf("writing %s: %w", path, err)
		}
		written++
	}
	return written, nil
}

// FormatUnitMarkdown renders a complete per-unit report card.
func FormatUnitMarkdown(u UnitReport, r FullReport) string {
	var b strings.Builder

	name := u.Symbol
	if name == "" {
		name = shortFile(u.Path)
	}

	// Header
	emoji := gradeEmoji(u.Grade)
	fmt.Fprintf(&b, "# %s `%s`\n\n", emoji, name)
	fmt.Fprintf(&b, "[← Back to Report Card](../REPORT_CARD.md#%s)\n\n", unitAnchor(u))
	b.WriteString("---\n\n")

	// Identity
	b.WriteString("## Identity\n\n")
	b.WriteString("| Field | Value |\n")
	b.WriteString("|-------|-------|\n")
	fmt.Fprintf(&b, "| **Unit ID** | `%s` |\n", u.UnitID)
	fmt.Fprintf(&b, "| **Type** | %s |\n", u.UnitType)
	fmt.Fprintf(&b, "| **Path** | `%s` |\n", u.Path)
	fmt.Fprintf(&b, "| **Language** | %s |\n", u.Language)
	if u.Symbol != "" {
		fmt.Fprintf(&b, "| **Symbol** | `%s` |\n", u.Symbol)
	}
	b.WriteString("\n")

	// Certification
	b.WriteString("## Certification\n\n")
	b.WriteString("| Field | Value |\n")
	b.WriteString("|-------|-------|\n")
	fmt.Fprintf(&b, "| **Grade** | %s **%s** |\n", emoji, u.Grade)
	fmt.Fprintf(&b, "| **Score** | %.1f%% |\n", u.Score*100)
	fmt.Fprintf(&b, "| **Status** | %s |\n", u.Status)
	fmt.Fprintf(&b, "| **Confidence** | %.0f%% |\n", u.Confidence*100)
	fmt.Fprintf(&b, "| **Certified** | %s |\n", formatDate(u.CertifiedAt))
	fmt.Fprintf(&b, "| **Expires** | %s |\n", formatDate(u.ExpiresAt))
	fmt.Fprintf(&b, "| **Source** | `%s` |\n", u.Source)
	b.WriteString("\n")

	// Dimensions
	if len(u.Dimensions) > 0 {
		b.WriteString("## Dimension Scores\n\n")
		b.WriteString("| Dimension | Score | Bar |\n")
		b.WriteString("|-----------|------:|-----|\n")
		for _, d := range sortedKeys(u.Dimensions) {
			score := u.Dimensions[d]
			bar := scoreBar(score, 20)
			fmt.Fprintf(&b, "| %s | %.1f%% | %s |\n", d, score*100, bar)
		}
		b.WriteString("\n")
	}

	// AI Observations
	aiObs, suggestions, otherObs := splitObservations(u.Observations)
	if len(aiObs) > 0 || len(suggestions) > 0 {
		b.WriteString("## 🤖 AI Assessment\n\n")
		for _, obs := range aiObs {
			// Strip the 🤖 prefix for cleaner display
			text := strings.TrimPrefix(obs, "🤖 ")
			fmt.Fprintf(&b, "%s\n\n", text)
		}
		if len(suggestions) > 0 {
			b.WriteString("### Suggestions\n\n")
			for _, s := range suggestions {
				text := strings.TrimPrefix(s, "💡 ")
				fmt.Fprintf(&b, "- %s\n", text)
			}
			b.WriteString("\n")
		}
	}

	// Other observations
	if len(otherObs) > 0 {
		b.WriteString("## Observations\n\n")
		for _, obs := range otherObs {
			fmt.Fprintf(&b, "- %s\n", obs)
		}
		b.WriteString("\n")
	}

	// Actions
	if len(u.Actions) > 0 {
		b.WriteString("## Required Actions\n\n")
		for _, a := range u.Actions {
			fmt.Fprintf(&b, "- [ ] %s\n", a)
		}
		b.WriteString("\n")
	}

	// Context
	b.WriteString("---\n\n")
	fmt.Fprintf(&b, "*Repository: `%s` · Commit: `%s` · Generated: %s*\n",
		r.Repository, r.CommitSHA, r.GeneratedAt)
	fmt.Fprintf(&b, "*Generated by [Certify](https://github.com/iksnae/code-certification)*\n")

	return b.String()
}

// splitObservations separates AI assessments, suggestions, and other observations.
func splitObservations(obs []string) (ai, suggestions, other []string) {
	for _, o := range obs {
		switch {
		case strings.HasPrefix(o, "🤖"):
			ai = append(ai, o)
		case strings.HasPrefix(o, "💡"):
			suggestions = append(suggestions, o)
		default:
			other = append(other, o)
		}
	}
	return
}

func formatDate(ts string) string {
	if len(ts) >= 10 {
		return ts[:10]
	}
	return ts
}

// gradeEmoji is defined in card.go

func scoreBar(score float64, width int) string {
	filled := int(score * float64(width))
	if filled > width {
		filled = width
	}
	return strings.Repeat("█", filled) + strings.Repeat("░", width-filled)
}
